//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPolicy
    {
        public CustomerPolicy()
        {
            this.CustomerPolicyMedias = new HashSet<CustomerPolicyMedia>();
            this.PolicyPayments = new HashSet<PolicyPayment>();
        }
    
        public int CustomerPolicyID { get; set; }
        public int CustomerID { get; set; }
        public int PolicyID { get; set; }
        public string PolicyNumber { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string PremiumFrequency { get; set; }
        public string VechileRegistrationNumber { get; set; }
        public decimal SumInsuredAmount { get; set; }
        public decimal ODPremiumAmount { get; set; }
        public decimal NetPremiumAmount { get; set; }
        public decimal TPPremiumAmount { get; set; }
        public decimal ServiceTax { get; set; }
        public decimal TotalPremiumAmount { get; set; }
        public string InsuredName { get; set; }
        public string PolicyStatus { get; set; }
        public Nullable<System.DateTime> PolicySubmitedDate { get; set; }
        public string LastPolicyNumber { get; set; }
        public Nullable<bool> IsHardCopy { get; set; }
        public Nullable<bool> IsRenewedPolicyReceived { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string Description { get; set; }
        public string UDK1 { get; set; }
        public string UDK2 { get; set; }
        public string UDK3 { get; set; }
        public string UDK4 { get; set; }
        public string UDK5 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdateByID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PolicyMaster PolicyMaster { get; set; }
        public virtual ICollection<CustomerPolicyMedia> CustomerPolicyMedias { get; set; }
        public virtual ICollection<PolicyPayment> PolicyPayments { get; set; }
    }
}
