//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceAgentEntities : DbContext
    {
        public InsuranceAgentEntities()
            : base("name=InsuranceAgentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomerMedia> CustomerMedias { get; set; }
        public DbSet<CustomerPolicy> CustomerPolicies { get; set; }
        public DbSet<CustomerPolicyInsured> CustomerPolicyInsureds { get; set; }
        public DbSet<CustomerPolicyMedia> CustomerPolicyMedias { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Family> Families { get; set; }
        public DbSet<PolicyCompany> PolicyCompanies { get; set; }
        public DbSet<PolicyMaster> PolicyMasters { get; set; }
        public DbSet<PolicyPayment> PolicyPayments { get; set; }
        public DbSet<PolicyType> PolicyTypes { get; set; }
    }
}
