//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyPayment
    {
        public int PaymentID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int CustomerPolicyID { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PaymentDetails { get; set; }
        public decimal CommissionAmount { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public string CommissionDetails { get; set; }
        public string UDK1 { get; set; }
        public string UDK2 { get; set; }
        public string UDK3 { get; set; }
        public string UDK4 { get; set; }
        public string UDK5 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedByID { get; set; }
    
        public virtual CustomerPolicy CustomerPolicy { get; set; }
    }
}
