//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyMaster
    {
        public PolicyMaster()
        {
            this.CustomerPolicies = new HashSet<CustomerPolicy>();
        }
    
        public int PolicyID { get; set; }
        public string PolicyName { get; set; }
        public string Description { get; set; }
        public int CompanyID { get; set; }
        public int PolicyTypeID { get; set; }
        public Nullable<int> LastCompanyID { get; set; }
        public string UDK1 { get; set; }
        public string UDK2 { get; set; }
        public string UDK3 { get; set; }
        public string UDK4 { get; set; }
        public string UDK5 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedByID { get; set; }
    
        public virtual ICollection<CustomerPolicy> CustomerPolicies { get; set; }
        public virtual PolicyCompany PolicyCompany { get; set; }
        public virtual PolicyType PolicyType { get; set; }
    }
}
